apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: html-landing-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:gm112/html-landing-page.git
        revision: HEAD
        directories:
          - path: "manifests"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:gm112/html-landing-page.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true 
