apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:me/argo-test.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
